# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [10]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [11]:
# Create a 1-dimensional NumPy array using np.array()
arr1d = np.array([1, 2, 3])
arr1d
# Create a 2-dimensional NumPy array using np.array()
arr2d = np.array([[1, 2, 3], [4, 2, 3]])
arr2d

# Create a 3-dimensional Numpy array using np.array()
arr3d = np.array([[1, 2, 3], [4, 2, 3], [5, 7, 2]])
arr3d

array([[1, 2, 3],
       [4, 2, 3],
       [5, 7, 2]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [12]:
def arrAttributes(arr):
    # how many array inside the arr [arr1, arr2, arr3]
    dim = arr.ndim
    # number of rows in columns
    size = arr.size
    # data type of array
    dtype = arr.dtype
    # (rows, cols)
    shape = arr.shape
    arr_type = type(arr)
    print("the dimension:", dim)
    print("the datatype of elements:", dtype)
    print("the size:", size)
    print("the type of array:", arr_type)

In [13]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
arrAttributes(arr1d)


the dimension: 1
the datatype of elements: int32
the size: 3
the type of array: <class 'numpy.ndarray'>


In [14]:
# Attributes of 2-dimensional array
arrAttributes(arr2d)


the dimension: 2
the datatype of elements: int32
the size: 6
the type of array: <class 'numpy.ndarray'>


In [15]:
# Attributes of 3-dimensional array
arrAttributes(arr3d)


the dimension: 2
the datatype of elements: int32
the size: 9
the type of array: <class 'numpy.ndarray'>


In [16]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(arr2d, columns=["f1", "f2", "f3"])

df

f1  f2  f3
0   1   2   3
1   4   2   3

In [17]:
# Create an array of shape (10, 2) with only ones
arr1 = np.ones((10, 2))
arr1

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
# Create an array of shape (7, 2, 3) of only zeros
arr0 = np.zeros((7, 2, 3))
arr0

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [19]:
# Create an array within a range of 0 and 100 with step 3
arr3 = np.arange(0, 100, 3)
arr3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [20]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
import random

ran_arr1 = np.random.randint(0, 10, size=(7, 2))
ran_arr1

array([[7, 0],
       [7, 9],
       [1, 7],
       [4, 1],
       [6, 6],
       [0, 9],
       [4, 1]])

In [21]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
ran_arr2 = np.random.rand(3, 5)
ran_arr2

array([[0.93350827, 0.34965532, 0.00446523, 0.74815761, 0.62722107],
       [0.30923571, 0.6344224 , 0.24748208, 0.33290928, 0.3953917 ],
       [0.15053629, 0.74100533, 0.89552114, 0.23787943, 0.36332719]])

In [22]:
# Set the random seed to 42
random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
ran_arr3 = np.random.randint(0, 10, size=(4, 6))
ran_arr3

array([[0, 8, 4, 5, 5, 2],
       [3, 9, 8, 7, 2, 4],
       [2, 8, 3, 1, 4, 4],
       [3, 9, 4, 9, 0, 6]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?
they are different

In [23]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
rarr = np.random.randint(1, 10, (3, 7))
rarr
# Find the unique numbers in the array you just created
np.unique(rarr)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
rarr

array([[3, 5, 8, 6, 3, 6, 8],
       [1, 7, 6, 2, 9, 9, 1],
       [1, 4, 5, 3, 1, 3, 5]])

In [25]:
# Find the 0'th index of the latest array you created
rarr[0]


array([3, 5, 8, 6, 3, 6, 8])

In [26]:
# Get the first 2 rows of latest array you created
rarr[0:2]

array([[3, 5, 8, 6, 3, 6, 8],
       [1, 7, 6, 2, 9, 9, 1]])

In [27]:
# Get the first 2 values of the first 2 rows of the latest array
val1 = rarr[0][0:2]
val2 = rarr[1][0:2]
val1

array([3, 5])

In [28]:
val2

array([1, 7])

In [29]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
rarr1 = np.random.randint(1, 10, (3, 5))
rarr0 = np.zeros((3,5))
rarr1

array([[9, 7, 5, 2, 7],
       [6, 9, 2, 6, 2],
       [2, 5, 8, 8, 9]])

In [30]:
rarr0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
# Add the two arrays together
arr = rarr1 + rarr0
arr

array([[9., 7., 5., 2., 7.],
       [6., 9., 2., 6., 2.],
       [2., 5., 8., 8., 9.]])

In [32]:
arr.shape

(3, 5)

In [33]:
# Create another array of ones of shape (5, 3)
one_arr = np.ones((5,3))
one_arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
# Try add the array of ones and the other most recent array together
arr + one_arr

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

 ##### it causes an error cause they are of different shape -> use the reshape function

In [35]:
add_arr = arr.reshape((5,3)) + one_arr
add_arr

array([[10.,  8.,  6.],
       [ 3.,  8.,  7.],
       [10.,  3.,  7.],
       [ 3.,  3.,  6.],
       [ 9.,  9., 10.]])

In [36]:
# Create another array of ones of shape (3, 5)
one_arr2 = np.ones((3, 5))

In [39]:
# Subtract the new array of ones from the other most recent array
sub_arr = one_arr2 - rarr1
sub_arr

array([[-8., -6., -4., -1., -6.],
       [-5., -8., -1., -5., -1.],
       [-1., -4., -7., -7., -8.]])

In [40]:
# Multiply the ones array with the latest array
mul_arr = sub_arr * one_arr2
mul_arr

array([[-8., -6., -4., -1., -6.],
       [-5., -8., -1., -5., -1.],
       [-1., -4., -7., -7., -8.]])

In [42]:
# Take the latest array to the power of 2 using '**'
# pow_arr = [x ** 2 for x in mul_arr]
pow_arr = mul_arr**2
pow_arr

array([[64., 36., 16.,  1., 36.],
       [25., 64.,  1., 25.,  1.],
       [ 1., 16., 49., 49., 64.]])

In [43]:
# Do the same thing with np.sq
pow_arr2 = np.square(mul_arr)
pow_arr2

array([[64., 36., 16.,  1., 36.],
       [25., 64.,  1., 25.,  1.],
       [ 1., 16., 49., 49., 64.]])

In [44]:
# Find the mean of the latest array using np.mean()
mean = np.mean(pow_arr)
mean

29.866666666666667

In [45]:
# Find the maximum of the latest array using np.max()
np.max(pow_arr)


64.0

In [46]:
# Find the minimum of the latest array using np.min()
np.min(pow_arr)

1.0

In [47]:
# Find the standard deviation of the latest array
np.std(pow_arr)

23.19156934941853

In [48]:
# Find the variance of the latest array
np.var(pow_arr)

537.848888888889

In [49]:
# Reshape the latest array to (3, 5, 1)
pow_reshape = pow_arr2.reshape((3, 5, 1))
pow_reshape

array([[[64.],
        [36.],
        [16.],
        [ 1.],
        [36.]],

       [[25.],
        [64.],
        [ 1.],
        [25.],
        [ 1.]],

       [[ 1.],
        [16.],
        [49.],
        [49.],
        [64.]]])

In [50]:
# Transpose the latest array
np.transpose(pow_reshape)

array([[[64., 25.,  1.],
        [36., 64., 16.],
        [16.,  1., 49.],
        [ 1., 25., 49.],
        [36.,  1., 64.]]])

What does the transpose do?

##### it make the rows elements in place of columns element and columns in place of rows

In [51]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
array1 = np.random.randint(0, 10, (3,3))
array2 = np.random.randint(0, 10, (3,2))
array1

array([[9, 3, 1],
       [3, 9, 4],
       [4, 7, 4]])

In [52]:
array2

array([[7, 2],
       [2, 6],
       [5, 5]])

In [53]:
# Perform a dot product on the two newest arrays you created
np.dot(array1, array2)

array([[74, 41],
       [59, 80],
       [62, 70]])

In [54]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
array1 = np.random.randint(0, 10, (4, 3))
array2 = np.random.randint(0, 10, (4, 3))
array1

array([[1, 3, 6],
       [6, 4, 2],
       [5, 6, 3],
       [6, 8, 6]])

In [55]:
# Perform a dot product on the two newest arrays you created
np.dot(array1, array2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

#### should transpose on of them so that the #cols of 1st = #rows of 2nd array

In [56]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(np.transpose(array1), array2)

array([[51, 69, 85],
       [58, 93, 87],
       [53, 88, 62]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

#### it happened because transposing one of them will reverse the rows and columns so dot product on matrix is satisfied

In [63]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr1 =  np.random.randint(0, 10,(4, 5))
arr2 =  np.random.randint(0, 10,(4, 5))

In [64]:
# Compare the two arrays with '>'
arr1 > arr2

array([[ True,  True, False,  True, False],
       [False,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False,  True, False]])

What happens when you compare the arrays with `>`?

##### it compare if each elements is equal to the corresponding element in the other array

In [65]:
# Compare the two arrays with '>='
arr1 >= arr2

array([[ True,  True, False,  True, False],
       [False,  True,  True,  True, False],
       [False, False, False, False, False],
       [ True, False,  True,  True, False]])

In [66]:
# Find which elements of the first array are greater than 7
# arr7 = [x>7 for x in arr1]
# arr7
# Find elements greater than 7
mask = arr1 > 7

# Apply mask to get the elements greater than 7
greater_than_7 = arr1[mask]
greater_than_7

array([9, 8, 8, 9, 8, 8])

In [67]:
# Which parts of each array are equal? (try using '==')
arr1 == arr2

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False,  True, False, False]])

In [69]:
# Sort one of the arrays you just created in ascending order
sorted_arr1 = np.sort(arr1)
sorted_arr1

array([[2, 3, 5, 8, 9],
       [2, 5, 8, 8, 9],
       [0, 1, 2, 4, 5],
       [1, 4, 4, 4, 8]])

In [70]:
# Sort the indexes of one of the arrays you just created
sorted_indexes_arr2 = np.argsort(arr2)

In [72]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(arr2)

9

In [73]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(arr1)

10

In [74]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(arr2, axis=1)

array([0, 4, 1, 0], dtype=int64)

In [77]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(arr2, axis=0)


array([1, 0, 1, 0, 0], dtype=int64)

In [79]:
# Create an array of normally distributed random numbers
normal_arr = np.random.normal(size=10)
normal_arr

array([-0.95114239,  1.30444695, -1.12029963,  0.22894352, -0.87202282,
        1.36609632,  0.09948974,  0.27917753,  0.39056066,  0.96082342])

In [82]:
# Create an array with 10 evenly spaced numbers between 1 and 100
last_arr =  np.linspace(1, 100, 10)
last_arr
len(last_arr)

10

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.